# Generated by Django 5.0.6 on 2024-06-12 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_connectionway'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectionway',
            options={'ordering': ['-created_at'], 'verbose_name': 'راه ارتباطی', 'verbose_name_plural': 'راههای ارتباطی'},
        ),
        migrations.AlterModelOptions(
            name='foreignlanguage',
            options={'ordering': ['-created_at'], 'verbose_name': 'زبان خارجه', 'verbose_name_plural': 'زبان های خارجه'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ['-created_at'], 'verbose_name': 'استان', 'verbose_name_plural': 'استان ها'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-created_at'], 'verbose_name': 'مهارت', 'verbose_name_plural': 'مهارت ها'},
        ),
        migrations.AlterModelOptions(
            name='studyfield',
            options={'ordering': ['-created_at'], 'verbose_name': 'رشته تحصیلی', 'verbose_name_plural': 'رشته های تحصیلی'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['-created_at'], 'verbose_name': 'دانشگاه', 'verbose_name_plural': 'دانشگاه ها'},
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
