# Generated by Django 5.0.6 on 2024-06-12 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_alter_city_options_alter_connectionway_options_and_more'),
        ('settings', '0006_city'),
    ]

    operations = [
    ]
