# Generated by Django 5.0.6 on 2024-06-26 13:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_merge_20240612_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureActivation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('feature', models.CharField(choices=[('RE', 'رزومه'), ('PP', 'اولویت بندی پروژه'), ('TE', 'تیم سازی'), ('TA', 'کار ویژه'), ('BE', 'آزمون بلبین'), ('NE', 'آزمون نئو'), ('SC', 'سناریو ها'), ('PR', 'ارائه ها'), ('EE', 'آزمون ورودی')], max_length=2, unique=True, verbose_name='فیجر')),
                ('activate', models.BooleanField(verbose_name='فعال')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
