# Generated by Django 5.0.6 on 2024-06-26 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_featureactivation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featureactivation',
            options={'ordering': ['-created_at'], 'verbose_name': 'فعال سازی فیچر', 'verbose_name_plural': 'فعال سازی فیچر ها'},
        ),
        migrations.RenameField(
            model_name='featureactivation',
            old_name='activate',
            new_name='active',
        ),
    ]
