# Generated by Django 5.0.6 on 2024-07-17 10:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0009_alter_featureactivation_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="City",
        ),
        migrations.DeleteModel(
            name="Province",
        ),
    ]
