# Generated by Django 5.0.6 on 2024-07-17 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0016_alter_education_university'),
        ('settings', '0011_province_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='University',
        ),
    ]
