# Generated by Django 5.0.6 on 2024-07-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_alter_studyfield_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
    ]
