# Generated by Django 5.0.6 on 2024-07-17 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_remove_project_study_fields_project_study_fields'),
        ('resume', '0018_alter_education_field'),
        ('settings', '0015_alter_university_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudyField',
        ),
    ]
