# Generated by Django 5.0.6 on 2024-09-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0017_studyfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyfield',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
    ]
