# Generated by Django 5.0.6 on 2024-09-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0018_alter_studyfield_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
    ]
