# Generated by Django 5.0.6 on 2025-01-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0020_alter_featureactivation_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureactivation',
            name='feature',
            field=models.CharField(choices=[('RE', 'رزومه'), ('PP', 'اولویت بندی پروژه'), ('TE', 'تیم سازی'), ('TA', 'کار ویژه'), ('BE', 'آزمون بلبین'), ('NE', 'آزمون نئو'), ('SC', 'سناریو ها'), ('PR', 'ارائه ها'), ('EE', 'آزمون ورودی'), ('PE', 'آزمون عمومی'), ('PL', 'پروپزال')], max_length=2, unique=True, verbose_name='فیجر'),
        ),
    ]
