# Generated by Django 5.2.5 on 2025-09-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0021_alter_featureactivation_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='phone_code',
            field=models.CharField(default='21', help_text='کد تلفن استان برای تولید کد تیم', max_length=3, verbose_name='کد تلفن استان'),
        ),
    ]
