version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - "db-data:/var/lib/postgresql/data"
    env_file:
      - .env
  redis:
    image: redis
    volumes:
      - redis-data:/data
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    entrypoint: ./entry.sh
    ports:
      - "8000:8000"
    volumes:
      - ./:/app

volumes:
  db-data:
  redis-data:


