FROM python:3.12

ENV PYTHONDONTWRITEBYTECODE 1

ENV PYTHONUNBUFFERED 1

WORKDIR /app

RUN pip install --upgrade poetry

COPY pyproject.toml poetry.lock ./

RUN poetry install

COPY . .

RUN chmod +x entry.sh

