# Generated by Django 5.0.6 on 2024-06-08 10:07

import apps.account.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.account.managers.BaseUserManager()),
            ],
        ),
    ]
