# Generated by Django 5.0.6 on 2024-06-08 10:32

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_options_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='', force_format=None, keep_meta=True, quality=-1, scale=None, size=[250, 250], upload_to='whatever'),
            preserve_default=False,
        ),
    ]
