# Generated by Django 5.0.6 on 2024-06-08 11:58

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(default="", verbose_name="آدرس"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(default="2000-02-01", verbose_name="تاریخ تولد"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("FE", "زن"), ("MA", "مرد")], default="", max_length=2, verbose_name="جنسیت"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="marriage_status",
            field=models.CharField(
                choices=[("FE", "زن"), ("MA", "مرد")], default="", max_length=2, verbose_name="وضعیت تاهل"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="military_status",
            field=models.CharField(
                blank=True,
                choices=[("EE", "معافیت تحصیلی"), ("PE", "معافیت دائم"), ("FS", "پایان خدمت"), ("IN", "مشمول")],
                max_length=2,
                null=True,
                verbose_name="وضعیت نظام وظیفه",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=["middle", "center"],
                force_format=None,
                keep_meta=True,
                quality=-1,
                scale=None,
                size=[250, 250],
                upload_to="account/avatar",
            ),
        ),
    ]
