# Generated by Django 5.0.6 on 2024-06-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_address_user_birth_date_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='marriage_status',
            field=models.CharField(choices=[('SI', 'مجرد'), ('MA', 'متاهل')], max_length=2, verbose_name='وضعیت تاهل'),
        ),
    ]
