# Generated by Django 5.0.6 on 2024-06-26 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_city_user_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='province',
        ),
    ]
