# Generated by Django 5.0.6 on 2024-08-24 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_user_community'),
        ('community', '0002_community_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='community.community', verbose_name='انجمن'),
        ),
    ]
