# Generated by Django 5.0.6 on 2024-09-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_user_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='لینک تلگرام'),
        ),
    ]
