# Generated by Django 5.0.6 on 2024-09-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_user_telegram_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس تلگرام'),
        ),
    ]
