# Generated by Django 5.0.6 on 2024-09-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_user_telegram_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_accespted_terms',
            field=models.BooleanField(default=False, verbose_name='آیا قوانین مسابقه را قبول کرده است؟'),
        ),
    ]
