# Generated by Django 5.0.6 on 2024-10-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_user_is_accespted_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_video',
            field=models.FileField(null=True, upload_to='account/personal_video'),
        ),
    ]
