# Generated by Django 5.0.6 on 2024-11-11 09:00

import apps.account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_user_personal_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personal_video',
            field=models.FileField(blank=True, null=True, upload_to='account/personal_video', validators=[apps.account.models.personal_video_file_type]),
        ),
    ]
