# Generated by Django 5.2.5 on 2025-09-12 13:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_connection'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('text', models.TextField(max_length=1000, verbose_name='متن نظر')),
                ('phase', models.CharField(blank=True, max_length=64, verbose_name='مرحله/بخش')),
                ('is_public', models.BooleanField(default=True, verbose_name='قابل نمایش')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده نظر')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='کاربر مقصد')),
            ],
            options={
                'verbose_name': 'نظر همتیمی (آیینه\u200cشو)',
                'verbose_name_plural': 'نظرات همتیمی (آیینه\u200cشو)',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
