# Generated by Django 5.2.5 on 2025-09-12 16:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_peerfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پیام مستقیم',
                'verbose_name_plural': 'پیام\u200cهای مستقیم',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['receiver', 'is_read'], name='account_dir_receive_22c7c9_idx'), models.Index(fields=['sender', 'receiver', 'created_at'], name='account_dir_sender__4f6c3e_idx')],
            },
        ),
    ]
