# Generated by Django 5.2.5 on 2025-09-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_directmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='ایمیل برای راه ارتباطی و دریافت اطلاعیه\u200cهای مهم', max_length=254, null=True, unique=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_address',
            field=models.CharField(blank=True, help_text='منسوخ شده - از ایمیل استفاده کنید', max_length=100, null=True, verbose_name='آدرس تلگرام'),
        ),
    ]
