# Generated by Django 5.2.5 on 2025-09-15 15:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0052_project_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='blog/images', verbose_name='تصویر اصلی')),
                ('video', models.FileField(blank=True, null=True, upload_to='blog/videos', verbose_name='ویدیو')),
                ('content', models.TextField(verbose_name='محتوای HTML (ریچ تکست)')),
                ('related_projects', models.ManyToManyField(blank=True, related_name='related_blog_posts', to='project.project', verbose_name='پروژه\u200cهای مرتبط')),
            ],
            options={
                'verbose_name': 'پست وبلاگ',
                'verbose_name_plural': 'پست\u200cهای وبلاگ',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('image', models.ImageField(upload_to='blog/post_images', verbose_name='تصویر')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.post')),
            ],
            options={
                'verbose_name': 'تصویر پست',
                'verbose_name_plural': 'تصاویر پست',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
