# Generated by Django 5.0.6 on 2024-06-24 12:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0007_merge_20240612_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='project/images', verbose_name='تصویر')),
                ('company', models.CharField(max_length=100, verbose_name='شرکت تعریف کننده پروژه')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('video', models.FileField(upload_to='project/videos', verbose_name='ویدئو')),
                ('study_fields', models.ManyToManyField(to='settings.studyfield', verbose_name='رشته های تحصیلی')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه ها',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
