# Generated by Django 5.0.6 on 2024-06-24 13:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_scenario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('title', models.CharField(verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('first_file', models.FileField(upload_to='', verbose_name='فایل اول')),
                ('second_file', models.FileField(upload_to='', verbose_name='فایل دوم')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_task', to='project.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'کارویژه',
                'verbose_name_plural': 'کارویژه ها',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
