# Generated by Django 5.0.6 on 2024-06-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='leader',
            field=models.CharField(max_length=30, null=True, verbose_name='نام راهبر پروژه'),
        ),
        migrations.AddField(
            model_name='project',
            name='leader_position',
            field=models.CharField(max_length=20, null=True, verbose_name='سمت راهبر پروژه'),
        ),
    ]
