# Generated by Django 5.0.6 on 2024-06-26 06:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_projectallocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalRepresentation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('file', models.FileField(upload_to='project/representations', verbose_name='فایل')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='representations', to='project.project', verbose_name='پروژه')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='representations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'ارائه نهایی',
                'verbose_name_plural': 'ارائه های نهایی',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
