# Generated by Django 5.0.6 on 2024-06-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_finalrepresentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='code',
            field=models.CharField(max_length=20, null=True, verbose_name='کد'),
        ),
    ]
