# Generated by Django 5.0.6 on 2024-06-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_project_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='کد'),
        ),
    ]
