# Generated by Django 5.0.6 on 2024-07-06 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_project_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='number',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='شماره'),
        ),
    ]
