# Generated by Django 5.0.6 on 2024-07-01 04:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('status', models.CharField(choices=[('A', 'قبول'), ('R', 'رد'), ('W', 'در انتظار')], default='W', max_length=1, verbose_name='وضعیت درخواست')),
                ('user_role', models.CharField(choices=[('C', 'ایجاد کننده'), ('M', 'عضو')], max_length=1, verbose_name='نقش در تیم')),
                ('description', models.TextField(null=True, verbose_name='توضیحات')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='project.team', verbose_name='تیم')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_requests', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درخواست هم تیمی',
                'verbose_name_plural': 'درخواست های هم تیمی',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
