# Generated by Django 5.0.6 on 2024-07-06 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_scenario_number'),
        ('project', '0010_teamrequest'),
    ]

    operations = [
    ]
