# Generated by Django 5.0.6 on 2024-07-07 05:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_merge_0009_scenario_number_0010_teamrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='number',
            field=models.PositiveSmallIntegerField(null=True, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='شماره'),
        ),
    ]
