# Generated by Django 5.0.6 on 2024-07-07 07:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_alter_scenario_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='number',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='شماره'),
        ),
    ]
