# Generated by Django 5.0.6 on 2024-07-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_alter_task_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='study_fields',
        ),
        migrations.AddField(
            model_name='project',
            name='study_fields',
            field=models.TextField(null=True),
        ),
    ]
