# Generated by Django 5.0.6 on 2024-07-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_alter_task_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='title',
            field=models.CharField(max_length=150, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=150, verbose_name='عنوان'),
        ),
    ]
