# Generated by Django 5.0.6 on 2024-07-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_remove_project_study_fields_project_study_fields'),
        ('settings', '0017_studyfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='study_fields',
        ),
        migrations.AddField(
            model_name='project',
            name='study_fields',
            field=models.ManyToManyField(to='settings.studyfield', verbose_name='رشته های تحصیلی'),
        ),
    ]
