# Generated by Django 5.0.6 on 2024-07-17 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_alter_scenario_title_alter_task_title'),
        ('project', '0017_remove_project_study_fields_project_study_fields'),
    ]

    operations = [
    ]
