# Generated by Django 5.0.6 on 2024-07-20 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_merge_20240717_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='count',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(5)], verbose_name='تعداد اعضا'),
        ),
    ]
