# Generated by Django 5.0.6 on 2024-08-03 11:40

import apps.project.services
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_team_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='title',
            field=models.CharField(max_length=50, validators=[apps.project.services.validate_persian, django.core.validators.MinLengthValidator(3)], verbose_name='نام'),
        ),
    ]
