# Generated by Django 5.0.6 on 2024-08-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_team_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='نمایش در صفحه اصلی'),
        ),
        migrations.AlterField(
            model_name='project',
            name='video',
            field=models.FileField(null=True, upload_to='project/videos', verbose_name='ویدئو'),
        ),
    ]
