# Generated by Django 5.0.6 on 2024-08-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_project_visible_alter_project_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='visible',
            field=models.BooleanField(default=False, verbose_name='نمایش در صفحه اصلی'),
        ),
    ]
