# Generated by Django 5.0.6 on 2024-08-04 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_alter_team_title'),
        ('project', '0021_alter_project_visible'),
    ]

    operations = [
    ]
