# Generated by Django 5.0.6 on 2024-08-17 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_merge_20240804_1022'),
        ('project', '0022_merge_20240814_1001'),
    ]

    operations = [
    ]
