# Generated by Django 5.0.6 on 2024-09-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_merge_20240817_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='نمایش در صفحه اصلی'),
        ),
    ]
