# Generated by Django 5.0.6 on 2024-09-07 14:28

import apps.project.services
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_alter_project_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(max_length=300, null=True, unique=True, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.CharField(max_length=300, verbose_name='شرکت تعریف کننده پروژه'),
        ),
        migrations.AlterField(
            model_name='project',
            name='leader',
            field=models.CharField(max_length=300, null=True, verbose_name='نام راهبر پروژه'),
        ),
        migrations.AlterField(
            model_name='project',
            name='leader_position',
            field=models.CharField(max_length=255, null=True, verbose_name='سمت راهبر پروژه'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=300, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='team',
            name='title',
            field=models.CharField(max_length=300, validators=[apps.project.services.validate_persian, django.core.validators.MinLengthValidator(3)], verbose_name='نام'),
        ),
    ]
