# Generated by Django 5.0.6 on 2024-09-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_alter_project_code_alter_project_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='project/videos', verbose_name='ویدئو'),
        ),
    ]
