# Generated by Django 5.0.6 on 2024-10-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_userscenariotaskfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='project/files', verbose_name='فایل'),
        ),
    ]
