# Generated by Django 5.0.6 on 2024-11-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_project_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='telegram_id',
            field=models.CharField(max_length=255, null=True, verbose_name='آدرس تلگرام'),
        ),
    ]
