# Generated by Django 5.0.6 on 2024-11-11 07:53

import apps.project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0029_project_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalrepresentation',
            name='file',
            field=models.FileField(upload_to='project/representations', validators=[apps.project.models.validate_file_type], verbose_name='فایل'),
        ),
    ]
