# Generated by Django 5.0.6 on 2024-11-20 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0031_alter_team_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='count',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(6)], verbose_name='تعداد اعضا'),
        ),
    ]
