# Generated by Django 5.0.6 on 2024-11-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0032_alter_team_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='create_date',
            field=models.DateField(null=True, verbose_name='تاریخ تشکیل تیم'),
        ),
    ]
