# Generated by Django 5.0.6 on 2024-11-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0033_team_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='second_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='فایل دوم'),
        ),
    ]
