# Generated by Django 5.0.6 on 2024-11-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0034_alter_task_second_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال'),
        ),
    ]
