# Generated by Django 5.0.6 on 2024-11-30 13:58

import apps.project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0035_task_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscenariotaskfile',
            name='file',
            field=models.FileField(upload_to='', validators=[apps.project.models.validate_user_task_file_type], verbose_name='فایل'),
        ),
    ]
