# Generated by Django 5.0.6 on 2024-12-29 09:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0036_alter_userscenariotaskfile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDerivatives',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('derivatives_type', models.CharField(choices=[('p', 'پروپوزال'), ('f', 'ارائه نهایی')], max_length=20, verbose_name='نوع مشتقات پروژه')),
                ('number', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='شماره')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('file', models.FileField(upload_to='', verbose_name='فایل')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_derivatives', to='project.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'مشتقات پروژه',
                'verbose_name_plural': 'مشتقات پروژه',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
