# Generated by Django 5.0.6 on 2024-12-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0037_projectderivatives'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectderivatives',
            old_name='file',
            new_name='first_file',
        ),
        migrations.AlterField(
            model_name='projectderivatives',
            name='derivatives_type',
            field=models.CharField(choices=[('P', 'پروپوزال'), ('F', 'ارائه نهایی')], max_length=20, verbose_name='نوع مشتقات پروژه'),
        ),
    ]
