# Generated by Django 5.0.6 on 2024-12-31 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0038_rename_file_projectderivatives_first_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscenariotaskfile',
            name='derivatives',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derivatives_files', to='project.projectderivatives', verbose_name='مشتقات پروژه'),
        ),
    ]
