# Generated by Django 5.2.5 on 2025-08-29 22:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0039_userscenariotaskfile_derivatives'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(help_text='نام کلیدواژه (مثال: python, django, machine-learning)', max_length=100, unique=True, verbose_name='نام تگ')),
                ('description', models.TextField(blank=True, help_text='توضیح مختصری درباره این کلیدواژه', null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'کلیدواژه',
                'verbose_name_plural': 'کلیدواژه ها',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='کلیدواژه\u200cهای مرتبط با این پروژه برای بهتر یافت شدن و پیشنهاد پروژه\u200cهای مرتبط', related_name='projects', to='project.tag', verbose_name='کلیدواژه ها'),
        ),
    ]
