# Generated by Django 5.2.5 on 2025-09-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0040_add_tags_to_projects'),
        ('settings', '0021_alter_featureactivation_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, help_text='وضعیت فعال/غیرفعال پروژه. پروژه\u200cهای غیرفعال قابل انتخاب نیستند اما مشاهده می\u200cشوند.', verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='project',
            name='visible',
            field=models.BooleanField(default=True, help_text='پروژه برای کاربران قابل مشاهده باشد', verbose_name='قابل مشاهده'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_active', 'visible'], name='project_pro_is_acti_04e83f_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_at'], name='project_pro_created_16407c_idx'),
        ),
    ]
