# Generated by Django 5.2.5 on 2025-09-03 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0041_add_is_active_to_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='telegram_id',
        ),
    ]
