# Generated by Django 5.2.5 on 2025-09-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0043_projectselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='auto_phase_transition',
            field=models.BooleanField(default=True, help_text='آیا فاز بر اساس تاریخ شروع و پایان تغییر کند؟', verbose_name='تغییر خودکار فاز'),
        ),
        migrations.AddField(
            model_name='project',
            name='selection_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='پایان انتخاب'),
        ),
        migrations.AddField(
            model_name='project',
            name='selection_phase',
            field=models.CharField(choices=[('BEFORE', 'قبل از انتخاب'), ('ACTIVE', 'در حال انتخاب'), ('FINISHED', 'پایان انتخاب')], default='BEFORE', max_length=10, verbose_name='فاز انتخاب'),
        ),
        migrations.AddField(
            model_name='project',
            name='selection_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='شروع انتخاب'),
        ),
    ]
