# Generated by Django 5.2.5 on 2025-09-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0044_project_auto_phase_transition_project_selection_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='summary',
            field=models.TextField(blank=True, help_text='خلاصه کوتاه و جذاب پروژه در حداکثر دو خط (200 کاراکتر)', max_length=200, null=True, verbose_name='خلاصه پروژه'),
        ),
    ]
