# Generated by Django 5.2.5 on 2025-09-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0045_project_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['category', 'name'], 'verbose_name': 'کلیدواژه', 'verbose_name_plural': 'کلیدواژه ها'},
        ),
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('SKILL', 'مهارت'), ('TECH', 'فناوری'), ('DOMAIN', 'حوزه'), ('KEYWORD', 'کلیدواژه')], default='KEYWORD', help_text='نوع تگ: مهارت، فناوری، حوزه یا کلیدواژه عمومی', max_length=10, verbose_name='دسته\u200cبندی'),
        ),
    ]
