# Generated by Django 5.2.5 on 2025-09-08 12:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0047_projectattractiveness'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('code', models.SlugField(unique=True, verbose_name='کد')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی تگ',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای تگ',
                'ordering': ['title'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('SKILL', 'مهارت'), ('TECH', 'فناوری'), ('DOMAIN', 'حوزه'), ('KEYWORD', 'کلیدواژه')], help_text='نوع تگ: مهارت، فناوری، حوزه یا کلیدواژه عمومی', max_length=10, verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='tag',
            name='category_ref',
            field=models.ForeignKey(blank=True, help_text='ارجاع دسته\u200cبندی دینامیک برای این تگ', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='project.tagcategory', verbose_name='دسته\u200cبندی (دینامیک)'),
        ),
    ]
