# Generated by Django 5.2.5 on 2025-09-08 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0050_guardrail_misc_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(help_text='به صورت خودکار از category_ref پر می\u200cشود.', max_length=50, verbose_name='کد دسته\u200cبندی (سازگاری قدیمی)'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='category_ref',
            field=models.ForeignKey(default=0, help_text='ارجاع به دسته\u200cبندی دینامیک', on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='project.tagcategory', verbose_name='دسته\u200cبندی'),
            preserve_default=False,
        ),
    ]
