# Generated by Django 5.2.5 on 2025-09-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('project', '0051_alter_tag_category_alter_tag_category_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='فقط کاربران این گروه\u200cها می\u200cتوانند پروژه را ببینند/انتخاب کنند. خالی یعنی همه گروه\u200cها.', related_name='projects', to='auth.group', verbose_name='گروه\u200cهای کاربری مرتبط'),
        ),
    ]
