# Generated by Django 5.2.5 on 2025-09-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0052_project_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='admin_message',
            field=models.TextField(blank=True, help_text='پیام اختیاری که روی صفحه پروژه نمایش داده می\u200cشود.', verbose_name='پیام ادمین برای صفحه پروژه'),
        ),
        migrations.AddField(
            model_name='project',
            name='deactivation_reason',
            field=models.CharField(blank=True, help_text='دلیل کوتاه که در صفحه پروژه نمایش داده می\u200cشود وقتی پروژه غیرفعال است.', max_length=200, verbose_name='علت غیرفعالسازی'),
        ),
    ]
