# Generated by Django 5.2.5 on 2025-09-15 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0053_project_admin_message_project_deactivation_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='dissolution_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان درخواست انحلال'),
        ),
        migrations.AddField(
            model_name='team',
            name='dissolution_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dissolution_requests', to=settings.AUTH_USER_MODEL, verbose_name='درخواست کننده انحلال'),
        ),
        migrations.AddField(
            model_name='team',
            name='is_dissolution_in_progress',
            field=models.BooleanField(default=False, verbose_name='در حال انحلال'),
        ),
        migrations.AddField(
            model_name='teamrequest',
            name='request_type',
            field=models.CharField(choices=[('JOIN', 'درخواست عضویت'), ('LEAVE', 'درخواست خروج'), ('INVITE', 'دعوت به عضویت'), ('DISSOLVE', 'درخواست انحلال تیم')], default='JOIN', max_length=10, verbose_name='نوع درخواست'),
        ),
        migrations.AddField(
            model_name='teamrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='made_team_requests', to=settings.AUTH_USER_MODEL, verbose_name='درخواست کننده'),
        ),
        migrations.AlterUniqueTogether(
            name='teamrequest',
            unique_together={('team', 'user', 'request_type', 'status')},
        ),
    ]
