# Generated by Django 5.2.5 on 2025-09-15 21:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0054_team_dissolution_requested_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamBuildingAnnouncement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='متن اطلاعیه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'اطلاعیه تیم\u200cسازی',
                'verbose_name_plural': 'اطلاعیه\u200cهای تیم\u200cسازی',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamBuildingVideoButton',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('title', models.CharField(max_length=100, verbose_name='عنوان دکمه')),
                ('video_url', models.URLField(verbose_name='لینک ویدیو')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_buttons', to='project.teambuildingannouncement', verbose_name='اطلاعیه')),
            ],
            options={
                'verbose_name': 'دکمه ویدیوی آموزشی',
                'verbose_name_plural': 'دکمه\u200cهای ویدیوی آموزشی',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
