# Generated by Django 5.2.5 on 2025-09-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0055_teambuildingannouncement_teambuildingvideobutton'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_building_stage',
            field=models.IntegerField(choices=[(1, 'مرحله اول - ناپایدار'), (2, 'مرحله دوم - ناپایدار'), (3, 'مرحله سوم - ناپایدار'), (4, 'مرحله پایدار')], default=4, verbose_name='مرحله تیم\u200cسازی'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_code',
            field=models.CharField(blank=True, help_text='کد تیم به صورت خودکار تولید می\u200cشود', max_length=10, unique=True, verbose_name='کد تیم'),
        ),
    ]
