# Generated by Django 5.2.5 on 2025-09-15 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0056_team_team_building_stage_team_team_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'درخواست تیم', 'verbose_name_plural': 'درخواست\u200cهای تیم'},
        ),
        migrations.AlterUniqueTogether(
            name='teamrequest',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='teamrequest',
            name='description',
            field=models.TextField(blank=True, default='-', verbose_name='توضیحات'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teamrequest',
            name='request_type',
            field=models.CharField(choices=[('JOIN', 'درخواست عضویت'), ('LEAVE', 'درخواست خروج'), ('INVITE', 'دعوت به عضویت'), ('DISSOLVE', 'درخواست انحلال تیم'), ('PROMOTE_DEPUTY', 'ارتقا به قائم مقام'), ('DEMOTE_DEPUTY', 'تنزل از قائم مقام'), ('TRANSFER_LEADERSHIP', 'انتقال رهبری')], default='JOIN', max_length=25, verbose_name='نوع درخواست'),
        ),
        migrations.AlterField(
            model_name='teamrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_requests', to=settings.AUTH_USER_MODEL, verbose_name='درخواست کننده'),
        ),
        migrations.AlterField(
            model_name='teamrequest',
            name='user_role',
            field=models.CharField(choices=[('C', 'سرگروه'), ('D', 'قائم مقام'), ('M', 'عضو')], max_length=1, verbose_name='نقش در تیم'),
        ),
        migrations.AddConstraint(
            model_name='teamrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('request_type', 'JOIN'), ('status', 'A')), fields=('team', 'user', 'request_type'), name='unique_active_team_membership'),
        ),
        migrations.AddConstraint(
            model_name='teamrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('request_type', 'JOIN'), ('status', 'A'), ('user_role', 'C')), fields=('team',), name='unique_team_leader'),
        ),
        migrations.AddConstraint(
            model_name='teamrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('request_type', 'JOIN'), ('status', 'A'), ('user_role', 'D')), fields=('team',), name='unique_team_deputy'),
        ),
    ]
