# Generated by Django 5.2.5 on 2025-09-16 11:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0057_alter_teamrequest_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('message', models.TextField(verbose_name='پیام')),
                ('is_edited', models.BooleanField(default=False, verbose_name='ویرایش شده')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ویرایش')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='project.team', verbose_name='تیم')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_messages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پیام چت تیم',
                'verbose_name_plural': 'پیام\u200cهای چت تیم',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamOnlineMeeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان جلسه')),
                ('meeting_url', models.URLField(verbose_name='لینک جلسه آنلاین')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='زمان برنامه\u200cریزی شده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_meetings', to='project.team', verbose_name='تیم')),
            ],
            options={
                'verbose_name': 'جلسه آنلاین تیم',
                'verbose_name_plural': 'جلسات آنلاین تیم',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamUnstableTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان کار')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('file', models.FileField(blank=True, null=True, upload_to='team_unstable_files/', verbose_name='فایل')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='مهلت انجام')),
                ('is_completed', models.BooleanField(default=False, verbose_name='تکمیل شده')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تکمیل')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='واگذار شده به')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unstable_tasks', to='project.team', verbose_name='تیم')),
            ],
            options={
                'verbose_name': 'کار بخش ناپایدار',
                'verbose_name_plural': 'کارهای بخش ناپایدار',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
