# Generated by Django 5.2.5 on 2025-09-17 12:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0058_teamchatmessage_teamonlinemeeting_teamunstabletask'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamBuildingStageDescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('page_type', models.CharField(choices=[('unstable_1_formation', 'صفحه تشکیل تیم ناپایدار مرحله 1'), ('unstable_2_formation', 'صفحه تشکیل تیم ناپایدار مرحله 2'), ('unstable_3_formation', 'صفحه تشکیل تیم ناپایدار مرحله 3'), ('stable_formation', 'صفحه تشکیل تیم پایدار'), ('team_page', 'صفحه تیم')], max_length=30, unique=True, verbose_name='نوع صفحه')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'توضیحات مراحل تیم\u200cسازی',
                'verbose_name_plural': 'توضیحات مراحل تیم\u200cسازی',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamBuildingSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('stage', models.IntegerField(choices=[(1, 'مرحله ناپایدار اول'), (2, 'مرحله ناپایدار دوم'), (3, 'مرحله ناپایدار سوم'), (4, 'مرحله پایدار')], verbose_name='مرحله تیم\u200cسازی')),
                ('control_type', models.CharField(choices=[('formation', 'صفحه تشکیل تیم'), ('team_page', 'صفحه تیم')], max_length=20, verbose_name='نوع کنترل')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='فعال')),
                ('custom_description', models.TextField(blank=True, verbose_name='توضیحات سفارشی')),
                ('min_team_size', models.IntegerField(default=2, verbose_name='حداقل اعضای تیم')),
                ('max_team_size', models.IntegerField(default=6, verbose_name='حداکثر اعضای تیم')),
                ('prevent_repeat_teammates', models.BooleanField(default=True, verbose_name='قانون منع همتیمی کراری')),
                ('allow_auto_completion', models.BooleanField(default=True, verbose_name='تکمیل خودکار تیم\u200cهای ناپایدار')),
                ('formation_deadline_hours', models.IntegerField(default=24, verbose_name='مهلت تشکیل تیم (ساعت)')),
            ],
            options={
                'verbose_name': 'تنظیمات تیم\u200cسازی',
                'verbose_name_plural': 'تنظیمات تیم\u200cسازی',
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('stage', 'control_type')},
            },
        ),
    ]
