# Generated by Django 5.2.5 on 2025-09-17 14:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0059_teambuildingstagedescription_teambuildingsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamrequest',
            name='request_type',
            field=models.CharField(choices=[('JOIN', 'درخواست عضویت'), ('LEAVE', 'درخواست خروج'), ('INVITE', 'دعوت به عضویت'), ('PROPOSE', 'پیشنهاد تشکیل تیم'), ('DISSOLVE', 'درخواست انحلال تیم'), ('PROMOTE_DEPUTY', 'ارتقا به قائم مقام'), ('DEMOTE_DEPUTY', 'تنزل از قائم مقام'), ('TRANSFER_LEADERSHIP', 'انتقال رهبری')], default='JOIN', max_length=25, verbose_name='نوع درخواست'),
        ),
        migrations.CreateModel(
            name='EmergencyActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('action_type', models.CharField(choices=[('EMERGENCY_DISSOLVE', 'انحلال اضطراری'), ('FORCE_REMOVE_MEMBER', 'حذف اجباری عضو'), ('FORCE_ADD_MEMBER', 'اضافه کردن اجباری عضو'), ('BYPASS_APPROVAL', 'غیرفعال کردن تایید')], max_length=30)),
                ('reason', models.TextField()),
                ('affected_users', models.JSONField(default=list)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_actions', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_logs', to='project.team')),
            ],
            options={
                'verbose_name': 'لاگ اقدامات اضطراری',
                'verbose_name_plural': 'لاگ اقدامات اضطراری',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmergencyBypass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('bypass_type', models.CharField(choices=[('DISSOLUTION_APPROVAL', 'عدم نیاز به تایید برای انحلال'), ('CAPACITY_LIMIT', 'عدم رعایت حد ظرفیت'), ('REPEAT_TEAMMATE_RULE', 'عدم رعایت قانون کراری')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('reason', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_bypasses', to='project.team')),
            ],
            options={
                'verbose_name': 'تنظیمات اضطراری',
                'verbose_name_plural': 'تنظیمات اضطراری',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
