# Generated by Django 5.0.6 on 2024-06-08 08:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('first_name', models.CharField(max_length=20, verbose_name='نام')),
                ('last_name', models.CharField(max_length=20, verbose_name='نام خانوادگی')),
                ('image', models.ImageField(null=True, upload_to='resume/images', verbose_name='تصویر')),
                ('mobile_number', models.CharField(max_length=11, verbose_name='شماره موبایل')),
                ('national_id', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('birth_date', models.DateField(verbose_name='تاریخ تولد')),
                ('gender', models.CharField(choices=[('0', 'زن'), ('1', 'مرد')], max_length=1, verbose_name='جنسیت')),
                ('military_status', models.CharField(blank=True, choices=[('0', 'معافیت تحصیلی'), ('1', 'معافیت دائم'), ('2', 'پایان خدمت'), ('3', 'مشمول')], max_length=1, null=True, verbose_name='وضعیت نظام وظیفه')),
                ('marriage_status', models.CharField(choices=[('0', 'مجرد'), ('1', 'متاهل')], max_length=1, verbose_name='وضعیت تاهل')),
                ('work_experience', models.BooleanField(default=False, verbose_name='سابقه شغلی')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resumes', to='settings.city', verbose_name='شهر')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resumes', to='settings.province', verbose_name='استان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'رزومه',
                'verbose_name_plural': 'رزومه ها',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('title', models.CharField(choices=[('0', 'لینکداین'), ('1', 'وبسایت')], max_length=1, verbose_name='عنوان پروژه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان پروژه')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_projects', to='resume.resume', verbose_name='رزومه(کاربر)')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه ها',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('language_name', models.CharField(max_length=1, verbose_name='نام زبان')),
                ('level', models.CharField(choices=[('0', 'مبتدی'), ('1', 'متوسط'), ('2', 'پیشرفته')], max_length=1, verbose_name='سطح تسلط')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='resume.resume', verbose_name='رزومه(کاربر)')),
            ],
            options={
                'verbose_name': 'زبان خارجی',
                'verbose_name_plural': 'زبان های خارجی',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('grade', models.CharField(choices=[('0', 'دیپلم'), ('1', 'کاردانی'), ('2', 'کارشناسی'), ('3', 'کارشناسی ارشد'), ('4', 'دکتری')], max_length=1, verbose_name='مقطع تحصیلی')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('until_now', models.BooleanField(default=False, verbose_name='مشغول به تحصیل')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.studyfield', verbose_name='رشته تحصیلی')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resumes', to='settings.university', verbose_name='دانشگاه')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='resume.resume', verbose_name='رزومه(کاربر)')),
            ],
            options={
                'verbose_name': 'مقطع تحصیلی',
                'verbose_name_plural': 'مقاطع تحصیلی',
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('title', models.CharField(choices=[('0', 'لینکداین'), ('1', 'وبسایت')], max_length=1, verbose_name='عنوان')),
                ('link', models.URLField(max_length=255, verbose_name='لینک')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='resume.resume', verbose_name='رزومه(کاربر)')),
            ],
            options={
                'verbose_name': 'راه ارتباطی',
                'verbose_name_plural': 'راه های ارتباطی',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('certificate_title', models.CharField(max_length=20, verbose_name='عنوان گواهی نامه')),
                ('institution', models.CharField(max_length=20, verbose_name='موسسه صادرکننده')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='تاریخ صدور')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('link', models.URLField(blank=True, max_length=255, null=True, verbose_name='لینک گواهی نامه')),
                ('file', models.FileField(blank=True, null=True, upload_to='resume/certificates', verbose_name='فایل گواهی نامه')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='resume.resume', verbose_name='رزومه(کاربر)')),
            ],
            options={
                'verbose_name': 'گواهی نامه',
                'verbose_name_plural': 'گواهی نامه ها',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('skill_name', models.CharField(max_length=1, null=True, verbose_name='نام مهارت')),
                ('text', models.CharField(max_length=20, null=True, verbose_name='متن مهارت')),
                ('level', models.CharField(choices=[('0', 'مبتدی'), ('1', 'متوسط'), ('2', 'پیشرفته')], max_length=1, verbose_name='سطح تسلط')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='resume.resume', verbose_name='رزومه(کاربر)')),
            ],
            options={
                'verbose_name': 'مهارت',
                'verbose_name_plural': 'مهارت ها',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('job_title', models.CharField(max_length=20, verbose_name='عنوان شغلی')),
                ('company_name', models.CharField(max_length=20, verbose_name='نام شرکت')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('until_now', models.BooleanField(default=False, verbose_name='مشغول به کار')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='resume.resume', verbose_name='رزومه(کاربر)')),
            ],
            options={
                'verbose_name': 'سابقه شغلی',
                'verbose_name_plural': 'سوابق شغلی',
            },
        ),
    ]
