# Generated by Django 5.0.6 on 2024-06-08 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-created_at'], 'verbose_name': 'گواهی نامه', 'verbose_name_plural': 'گواهی نامه ها'},
        ),
        migrations.AlterModelOptions(
            name='connection',
            options={'ordering': ['-created_at'], 'verbose_name': 'راه ارتباطی', 'verbose_name_plural': 'راه های ارتباطی'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-created_at'], 'verbose_name': 'مقطع تحصیلی', 'verbose_name_plural': 'مقاطع تحصیلی'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['-created_at'], 'verbose_name': 'زبان خارجی', 'verbose_name_plural': 'زبان های خارجی'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'پروژه', 'verbose_name_plural': 'پروژه ها'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-created_at'], 'verbose_name': 'رزومه', 'verbose_name_plural': 'رزومه ها'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-created_at'], 'verbose_name': 'مهارت', 'verbose_name_plural': 'مهارت ها'},
        ),
        migrations.AlterModelOptions(
            name='workexperience',
            options={'ordering': ['-created_at'], 'verbose_name': 'سابقه شغلی', 'verbose_name_plural': 'سوابق شغلی'},
        ),
        migrations.RemoveField(
            model_name='resume',
            name='city',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='image',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='province',
        ),
        migrations.AddField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('0', 'ایجاد شده'), ('1', 'تایید شده')], default='0', max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
