# Generated by Django 5.0.6 on 2024-06-08 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_certificate_options_alter_connection_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='address',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='marriage_status',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='military_status',
        ),
    ]
