# Generated by Django 5.0.6 on 2024-06-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_remove_resume_address_remove_resume_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='steps',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
