# Generated by Django 5.0.6 on 2024-06-08 15:00

import apps.resume.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_resume_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('CR', 'ایجاد شده'), ('CO', 'تایید شده')], default='0', max_length=2, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='steps',
            field=models.JSONField(default=apps.resume.models.default_resume_step),
        ),
    ]
