# Generated by Django 5.0.6 on 2024-06-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_resume_status_alter_resume_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('CR', 'ایجاد شده'), ('CO', 'تایید شده')], default='CR', max_length=2, verbose_name='وضعیت'),
        ),
    ]
