# Generated by Django 5.0.6 on 2024-06-09 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_alter_resume_status'),
        ('settings', '0002_foreignlanguage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='grade',
            field=models.CharField(choices=[('DI', 'دیپلم'), ('AD', 'کاردانی'), ('BA', 'کارشناسی'), ('MA', 'کارشناسی ارشد'), ('PD', 'دکتری')], max_length=3, verbose_name='مقطع تحصیلی'),
        ),
        migrations.AlterField(
            model_name='language',
            name='language_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.foreignlanguage', verbose_name='نام زبان'),
        ),
    ]
