# Generated by Django 5.0.6 on 2024-06-10 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_alter_resume_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='until_now',
        ),
    ]
