# Generated by Django 5.0.6 on 2024-06-12 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0009_remove_education_until_now"),
        ("settings", "0003_skill"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workexperience",
            name="until_now",
        ),
        migrations.AlterField(
            model_name="skill",
            name="skill_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="settings.skill",
                verbose_name="نام مهارت",
            ),
        ),
    ]
