# Generated by Django 5.0.6 on 2024-06-12 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0010_remove_workexperience_until_now_and_more"),
        ("settings", "0004_connectionway"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connection",
            name="title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="settings.connectionway",
                verbose_name="عنوان",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=50, verbose_name="عنوان پروژه"),
        ),
    ]
