# Generated by Django 5.0.6 on 2024-06-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_alter_connection_title_alter_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='level',
            field=models.CharField(choices=[('EL', 'مبتدی'), ('IN', 'متوسط'), ('AD', 'پیشرفته')], max_length=2, verbose_name='سطح تسلط'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('EL', 'مبتدی'), ('IN', 'متوسط'), ('AD', 'پیشرفته')], max_length=2, verbose_name='سطح تسلط'),
        ),
    ]
