# Generated by Django 5.0.6 on 2024-06-12 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0011_alter_connection_title_alter_project_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resume",
            name="work_experience",
        ),
    ]
