# Generated by Django 5.0.6 on 2024-06-15 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_alter_language_level_alter_skill_level'),
        ('resume', '0012_remove_resume_work_experience'),
    ]

    operations = [
    ]
