# Generated by Django 5.0.6 on 2024-06-15 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_merge_20240612_1619'),
        ('resume', '0013_merge_20240615_0900'),
    ]

    operations = [
    ]
