# Generated by Django 5.0.6 on 2024-06-20 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_merge_20240615_1040'),
        ('settings', '0007_merge_20240612_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='settings.skill', verbose_name='نام مهارت'),
        ),
    ]
