# Generated by Django 5.0.6 on 2024-07-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0015_alter_skill_skill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='university',
            field=models.TextField(null=True),
        ),
    ]
