# Generated by Django 5.0.6 on 2024-07-17 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0016_alter_education_university'),
        ('settings', '0013_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resumes', to='settings.university', verbose_name='دانشگاه'),
        ),
    ]
