# Generated by Django 5.0.6 on 2024-07-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0017_alter_education_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='field',
            field=models.TextField(null=True),
        ),
    ]
