# Generated by Django 5.0.6 on 2024-07-17 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0018_alter_education_field'),
        ('settings', '0017_studyfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.studyfield', verbose_name='رشته تحصیلی'),
        ),
    ]
