# Generated by Django 5.0.6 on 2024-08-04 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0019_alter_education_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='expiration_date',
        ),
    ]
