# Generated by Django 5.0.6 on 2024-08-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0020_remove_certificate_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(null=True, verbose_name='تاریخ شروع پروژه'),
        ),
    ]
