# Generated by Django 5.0.6 on 2024-08-18 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0021_project_start_date'),
        ('settings', '0017_studyfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='telegram',
            field=models.URLField(max_length=255, null=True, verbose_name='لینک تلگرام'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='لینک'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='settings.connectionway', verbose_name='عنوان'),
        ),
    ]
