# Generated by Django 5.0.6 on 2024-08-21 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0022_connection_telegram_alter_connection_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='text',
        ),
    ]
