# Generated by Django 5.0.6 on 2024-08-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0023_remove_skill_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='telegram',
            field=models.CharField(max_length=50, null=True, verbose_name='لینک تلگرام'),
        ),
    ]
