# Generated by Django 5.0.6 on 2024-09-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0024_alter_connection_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='لینک'),
        ),
    ]
