# Generated by Django 5.0.6 on 2024-09-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0025_alter_connection_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_title',
            field=models.CharField(max_length=255, verbose_name='عنوان گواهی نامه'),
        ),
    ]
