# Generated by Django 5.0.6 on 2024-09-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0026_alter_certificate_certificate_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان پروژه'),
        ),
    ]
