# Generated by Django 5.0.6 on 2024-10-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0028_alter_certificate_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='company_name',
            field=models.CharField(max_length=255, verbose_name='نام شرکت'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='job_title',
            field=models.CharField(max_length=255, verbose_name='عنوان شغلی'),
        ),
    ]
