# Generated by Django 5.2.5 on 2025-09-15 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0029_alter_workexperience_company_name_and_more'),
        ('settings', '0021_alter_featureactivation_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='team_formation_province',
            field=models.ForeignKey(blank=True, help_text='استان محل سکونت/کار برای تشکیل تیم. این فیلد برای برنامه\u200cریزی جلسات حضوری استانی استفاده می\u200cشود.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_formation_resumes', to='settings.province', verbose_name='استان محل تشکیل تیم'),
        ),
    ]
