# Generated by Django 5.2.5 on 2025-09-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0030_resume_team_formation_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='manual_role_tags',
            field=models.JSONField(blank=True, default=list, help_text='برچسب\u200cهای نقش تیمی که کاربر به صورت دستی انتخاب کرده (حداکثر 4 مورد)', verbose_name='برچسب\u200cهای نقش دستی'),
        ),
    ]
