# Generated by Django 5.2.5 on 2025-09-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='object_id',
            field=models.CharField(max_length=36, verbose_name='شناسه آبجکت'),
        ),
    ]
