# Generated by Django 5.2.5 on 2025-09-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comment_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmoderationlog',
            name='new_status',
            field=models.CharField(choices=[('PENDING', 'در انتظار تایید'), ('APPROVED', 'تایید شده'), ('REJECTED', 'رد شده')], default='APPROVED', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentmoderationlog',
            name='previous_status',
            field=models.CharField(choices=[('PENDING', 'در انتظار تایید'), ('APPROVED', 'تایید شده'), ('REJECTED', 'رد شده')], default='PENDING', max_length=10),
            preserve_default=False,
        ),
    ]
