# Generated by Django 5.0.6 on 2024-08-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_commonquestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('contact_number', models.CharField(max_length=11, verbose_name='شماره تماس')),
            ],
            options={
                'verbose_name': 'اطلاعات تماس',
                'verbose_name_plural': 'اطلاعات تماس',
            },
        ),
    ]
