# Generated by Django 5.0.6 on 2024-08-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_contactinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(null=True, upload_to='public/about_us', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما',
            },
        ),
    ]
