# Generated by Django 5.0.6 on 2024-08-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'قانون مسابقه',
                'verbose_name_plural': 'قوانین مسابقه',
            },
        ),
    ]
