# Generated by Django 5.0.6 on 2024-08-03 07:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_competitionrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('full_name', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='آدرس ایمیل')),
                ('message_title', models.CharField(max_length=50, verbose_name='موضوع پیام')),
                ('message_body', models.TextField(verbose_name='متن پیام')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'تماس با ما',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
