# Generated by Django 5.0.6 on 2024-08-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinformation',
            name='instagram',
            field=models.CharField(blank=True, null=True, verbose_name='اینستاگرام'),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='linked_in',
            field=models.CharField(blank=True, null=True, verbose_name='لینکداین'),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='telegram',
            field=models.CharField(blank=True, null=True, verbose_name='تلگرام'),
        ),
    ]
