# Generated by Django 5.0.6 on 2024-08-31 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_contactinformation_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinformation',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='contact_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تماس'),
        ),
    ]
