# Generated by Django 5.0.6 on 2024-09-30 07:03

import apps.utils.utility
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0009_alter_contactinformation_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='mobile_number',
            field=models.CharField(max_length=11, null=True, validators=[apps.utils.utility.mobile_validator], verbose_name='شماره تماس'),
        ),
    ]
