# Generated by Django 5.0.6 on 2024-10-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0011_ticket_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('USER', 'user')], max_length=5, null=True, verbose_name='نقش کاربر'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'open'), ('CLOSED', 'closed')], max_length=6, verbose_name='وضعیت'),
        ),
    ]
