# Generated by Django 5.0.6 on 2024-10-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0012_comment_user_role_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان'),
        ),
    ]
