# Generated by Django 5.0.6 on 2024-10-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0013_ticket_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='فایل'),
        ),
    ]
