# Generated by Django 5.0.6 on 2024-10-06 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0015_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='public.department', verbose_name='دپارتمان'),
        ),
    ]
