# Generated by Django 5.0.6 on 2024-11-11 13:59

import apps.public.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0017_ticket_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[apps.public.models.validate_ticket_file], verbose_name='فایل'),
        ),
    ]
