# Generated by Django 5.2.5 on 2025-09-17 20:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0021_announcement_userannouncementstate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernotification',
            options={'ordering': ['-created_at'], 'verbose_name': 'اعلان کاربر', 'verbose_name_plural': 'اعلان\u200cهای کاربر'},
        ),
        migrations.AddField(
            model_name='usernotification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddIndex(
            model_name='usernotification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='public_user_user_id_e20c84_idx'),
        ),
    ]
