# Generated by Django 5.2.5 on 2025-09-18 20:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0022_alter_usernotification_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationreceipt',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='notificationreceipt',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at'], 'verbose_name': 'اعلان', 'verbose_name_plural': 'اعلانات'},
        ),
        migrations.AlterModelOptions(
            name='usernotification',
            options={'ordering': ['-created_at'], 'verbose_name': 'آگهی کاربر', 'verbose_name_plural': 'آگهی\u200cهای کاربر'},
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='active',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='body',
        ),
        migrations.AddField(
            model_name='announcement',
            name='description',
            field=models.TextField(default='-', verbose_name='توضیحات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(default='-', upload_to='announcements/images', verbose_name='تصویر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال؟'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='کاربران هدف'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.CreateModel(
            name='AnnouncementReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='public.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'وضعیت اعلان\u200cهای کاربر',
                'verbose_name_plural': 'وضعیت اعلان\u200cهای کاربران',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='NotificationReceipt',
        ),
        migrations.AddConstraint(
            model_name='announcementreceipt',
            constraint=models.UniqueConstraint(fields=('announcement', 'user'), name='unique_announcement_receipt_per_user'),
        ),
    ]
