# Generated by Django 5.0.6 on 2024-08-22 09:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('title', models.CharField(max_length=50, verbose_name='نام انجمن')),
                ('code', models.CharField(max_length=6, unique=True, verbose_name='کد انجمن')),
            ],
            options={
                'verbose_name': 'انجمن علمی',
                'verbose_name_plural': 'انجمن های علمی',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
