# Generated by Django 5.0.6 on 2024-08-22 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='manager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_communities', to=settings.AUTH_USER_MODEL, verbose_name='مدیر انجمن'),
        ),
    ]
