# Generated by Django 5.0.6 on 2024-09-05 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_community_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='representer_community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='represented_communities', to='community.community', verbose_name='انجمن معرف'),
        ),
    ]
