# Generated by Django 5.0.6 on 2024-10-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_communityresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityresource',
            name='file',
            field=models.FileField(upload_to='community/file', verbose_name='فایل'),
        ),
    ]
