# Generated by Django 5.0.6 on 2024-09-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_community_representer_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='title',
            field=models.CharField(max_length=400, verbose_name='نام انجمن'),
        ),
    ]
