# Generated by Django 5.0.6 on 2024-10-07 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_community_title'),
        ('community', '0004_alter_communityresource_file'),
    ]

    operations = [
    ]
