# Generated by Django 5.0.6 on 2024-06-15 08:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_belbinquestion_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='BelbinAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('answer', models.TextField(verbose_name='جواب')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belbin_answer_question', to='exam.belbinquestion', verbose_name='جواب ها')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
