# Generated by Django 5.0.6 on 2024-06-15 10:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_useranswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeoQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='عنوان سوال')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='شماره')),
            ],
            options={
                'verbose_name': 'سوال آزمون نئو',
                'verbose_name_plural': 'سوال های آزمون نئو',
            },
        ),
    ]
