# Generated by Django 5.0.6 on 2024-06-15 10:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_neoquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeoOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('options', models.CharField(choices=[('QA', 'کاملا موافقم'), ('A', 'موافقم'), ('NI', 'نظری ندارم'), ('DA', 'مخالفم'), ('QDA', 'کاملا مخالفم')], max_length=3, verbose_name='گزینه')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.neoquestion', verbose_name='سوال')),
            ],
            options={
                'verbose_name': 'گزینه آزمون نئو',
                'verbose_name_plural': 'گزینه های آزمون نئو',
            },
        ),
    ]
