# Generated by Django 5.0.6 on 2024-06-15 10:29

import apps.exam.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_neooption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'پاسخ کاربر', 'verbose_name_plural': 'پاسخ های کاربر'},
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer',
            field=models.JSONField(default=apps.exam.models.default_user_answer, verbose_name='پاسخ'),
        ),
    ]
