# Generated by Django 5.0.6 on 2024-06-15 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_alter_useranswer_options_alter_useranswer_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neooption',
            old_name='options',
            new_name='option',
        ),
    ]
