# Generated by Django 5.0.6 on 2024-06-16 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_rename_options_neooption_option'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='belbinanswer',
            options={'verbose_name': 'گزینه آزمون بلبین', 'verbose_name_plural': 'گزینه های آزمون بلبین'},
        ),
        migrations.AlterModelOptions(
            name='belbinquestion',
            options={'verbose_name': 'سوال آزمون بلبین', 'verbose_name_plural': 'سوال های آزمون بلبین'},
        ),
    ]
