# Generated by Django 5.0.6 on 2024-06-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_alter_belbinanswer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='neoquestion',
            name='option',
            field=models.CharField(choices=[('QA', 'کاملا موافقم'), ('A', 'موافقم'), ('NI', 'نظری ندارم'), ('DA', 'مخالفم'), ('QDA', 'کاملا مخالفم')], default='NI', max_length=3, verbose_name='گزینه'),
        ),
    ]
