# Generated by Django 5.0.6 on 2024-06-18 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_neoquestion_option'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NeoOption',
        ),
    ]
