# Generated by Django 5.0.6 on 2024-06-18 06:46

import apps.exam.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_delete_neooption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neoquestion',
            options={'ordering': ['-created_at'], 'verbose_name': 'سوال آزمون نئو', 'verbose_name_plural': 'سوال های آزمون نئو'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='neoquestion',
            name='option',
            field=models.CharField(choices=[('0', 'کاملا موافقم'), ('1', 'موافقم'), ('2', 'نظری ندارم'), ('3', 'مخالفم'), ('4', 'کاملا مخالفم')], default='0', max_length=3, verbose_name='گزینه'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer',
            field=models.JSONField(default=apps.exam.models.default_user_answer),
        ),
    ]
