# Generated by Django 5.0.6 on 2024-06-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_alter_neoquestion_options_alter_useranswer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='belbinanswer',
            options={'ordering': ['-created_at'], 'verbose_name': 'گزینه آزمون بلبین', 'verbose_name_plural': 'گزینه های آزمون بلبین'},
        ),
        migrations.AlterModelOptions(
            name='belbinquestion',
            options={'ordering': ['-created_at'], 'verbose_name': 'سوال آزمون بلبین', 'verbose_name_plural': 'سوال های آزمون بلبین'},
        ),
        migrations.AddField(
            model_name='neoquestion',
            name='question_type',
            field=models.CharField(choices=[('ES', 'تجربه پذیری'), ('LS', 'وظیفه شناسی'), ('ES', 'برونگرایی'), ('CS', 'سازگاری'), ('NS', 'روان رنجوری')], default='ES', max_length=2, verbose_name='نوع سوال'),
        ),
    ]
