# Generated by Django 5.0.6 on 2024-06-18 10:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_alter_neoquestion_options_alter_useranswer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('title', models.TextField(verbose_name='عنوان')),
                ('time', models.PositiveIntegerField(verbose_name='زمان')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوال ها',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='belbinanswer',
            options={'ordering': ['-created_at'], 'verbose_name': 'گزینه آزمون بلبین', 'verbose_name_plural': 'گزینه های آزمون بلبین'},
        ),
        migrations.AlterModelOptions(
            name='belbinquestion',
            options={'ordering': ['-created_at'], 'verbose_name': 'سوال آزمون بلبین', 'verbose_name_plural': 'سوال های آزمون بلبین'},
        ),
        migrations.CreateModel(
            name='GeneralQuestionAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('title', models.TextField(verbose_name='عنوان گزینه')),
                ('score', models.PositiveIntegerField(verbose_name='امتیاز')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_question_answer', to='exam.generalquestion')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
