# Generated by Django 5.0.6 on 2024-06-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_generalquestion_alter_belbinanswer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalquestionanswer',
            name='correct_answer',
            field=models.BooleanField(default=False, verbose_name='جواب درست'),
        ),
    ]
