# Generated by Django 5.0.6 on 2024-06-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_alter_belbinanswer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neoquestion',
            name='question_type',
            field=models.CharField(choices=[('ES', 'تجربه پذیری'), ('LS', 'وظیفه شناسی'), ('OS', 'برونگرایی'), ('CS', 'سازگاری'), ('NS', 'روان رنجوری')], default='ES', max_length=2, verbose_name='نوع سوال'),
        ),
    ]
