# Generated by Django 5.0.6 on 2024-06-19 06:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_alter_neoquestion_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('option_number', models.PositiveIntegerField(unique=True, verbose_name='شماره')),
                ('option', models.CharField(max_length=100, unique=True, verbose_name='گزینه')),
                ('option_score', models.PositiveSmallIntegerField(verbose_name='نمره')),
            ],
            options={
                'verbose_name': 'گزینه آزمون',
                'verbose_name_plural': 'گزینه های آزمون',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('exam_type', models.CharField(choices=[('N', 'نئو'), ('E', 'ورودی')], max_length=1, verbose_name='نوع آزمون')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='شماره')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='عنوان سوال')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='وزن سوال')),
            ],
            options={
                'verbose_name': 'سوال آزمون',
                'verbose_name_plural': 'سوال های آزمون',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='NeoQuestion',
        ),
        migrations.AddField(
            model_name='examoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.examquestion', verbose_name='سوال'),
        ),
    ]
