# Generated by Django 5.0.6 on 2024-06-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_generalquestionanswer_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalquestion',
            name='number',
            field=models.PositiveIntegerField(default=4, unique=True),
            preserve_default=False,
        ),
    ]
