# Generated by Django 5.0.6 on 2024-06-18 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_generalquestion_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralQuestionAnswer',
            new_name='GeneralQuestionOption',
        ),
    ]
