# Generated by Django 5.0.6 on 2024-06-19 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_examoption_examquestion_delete_neoquestion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamOption',
            new_name='NeoOption',
        ),
        migrations.RenameModel(
            old_name='ExamQuestion',
            new_name='NeoQuestion',
        ),
    ]
