# Generated by Django 5.0.6 on 2024-06-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_rename_examoption_neooption_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neooption',
            options={'ordering': ['-created_at'], 'verbose_name': 'گزینه آزمون نئو', 'verbose_name_plural': 'گزینه های آزمون نئو'},
        ),
        migrations.AlterModelOptions(
            name='neoquestion',
            options={'ordering': ['-created_at'], 'verbose_name': 'سوال آزمون نئو', 'verbose_name_plural': 'سوال های آزمون نئو'},
        ),
        migrations.RemoveField(
            model_name='neoquestion',
            name='exam_type',
        ),
        migrations.RemoveField(
            model_name='neoquestion',
            name='score',
        ),
        migrations.AddField(
            model_name='neoquestion',
            name='question_type',
            field=models.CharField(choices=[('ES', 'تجربه پذیری'), ('DS', 'وظیفه شناسی'), ('OS', 'برونگرایی'), ('CS', 'سازگاری'), ('NS', 'روان رنجوری')], default='ES', max_length=2, verbose_name='نوع سوال'),
        ),
    ]
