# Generated by Django 5.0.6 on 2024-06-19 09:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_rename_generalquestionanswer_generalquestionoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralQuestionExam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('title', models.CharField(verbose_name='عنوان')),
                ('time', models.PositiveIntegerField(verbose_name='زمان')),
            ],
            options={
                'verbose_name': 'آزمون عمومی',
                'verbose_name_plural': 'آزمون های عمومی',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='generalquestion',
            name='time',
        ),
        migrations.AddField(
            model_name='generalquestion',
            name='exam',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='general_question_exam', to='exam.generalquestionexam', verbose_name='سوال های عمومی'),
            preserve_default=False,
        ),
    ]
