# Generated by Django 5.0.6 on 2024-06-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_alter_neooption_options_alter_neoquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neooption',
            name='option_number',
            field=models.PositiveSmallIntegerField(verbose_name='شماره'),
        ),
    ]
