# Generated by Django 5.0.6 on 2024-06-19 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_generalquestionexam_remove_generalquestion_time_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralQuestionExam',
            new_name='GeneralExam',
        ),
    ]
