# Generated by Django 5.0.6 on 2024-06-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0018_rename_generalquestionexam_generalexam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalexam',
            name='title',
            field=models.CharField(unique=True, verbose_name='عنوان'),
        ),
    ]
