# Generated by Django 5.0.6 on 2024-06-20 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0018_alter_neooption_option_number'),
        ('exam', '0019_alter_generalexam_title'),
    ]

    operations = [
    ]
