# Generated by Django 5.0.6 on 2024-06-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0020_merge_20240620_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalquestionoption',
            name='score',
        ),
        migrations.AddField(
            model_name='generalquestion',
            name='score',
            field=models.PositiveIntegerField(default=3, verbose_name='امتیاز'),
            preserve_default=False,
        ),
    ]
