# Generated by Django 5.0.6 on 2024-06-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0020_merge_20240620_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='neoquestion',
            name='options',
            field=models.JSONField(default=dict, null=True, verbose_name='گزینه ها'),
        ),
    ]
