# Generated by Django 5.0.6 on 2024-06-27 04:59

import apps.exam.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0021_neoquestion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neoquestion',
            name='options',
            field=models.JSONField(default=apps.exam.models.default_neo_options, null=True, verbose_name='گزینه ها'),
        ),
    ]
