# Generated by Django 5.0.6 on 2024-06-26 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0021_remove_generalquestionoption_score_and_more'),
        ('project', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalexam',
            name='mode',
            field=models.CharField(choices=[('PU', 'عمومی'), ('EN', 'ورودی')], default='PU', max_length=2, verbose_name='نوع'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalexam',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_exam_project', to='project.project', verbose_name='پروژه'),
        ),
    ]
