# Generated by Django 5.0.6 on 2024-06-30 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0022_alter_neoquestion_options'),
        ('exam', '0022_generalexam_mode_generalexam_project'),
    ]

    operations = [
    ]
