# Generated by Django 5.0.6 on 2024-07-01 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0022_alter_neoquestion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useranswer',
            options={'ordering': ['-created_at'], 'verbose_name': 'پاسخ کاربر', 'verbose_name_plural': 'پاسخ های کاربران'},
        ),
    ]
