# Generated by Django 5.0.6 on 2024-06-30 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0023_merge_20240630_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useranswer',
            options={'ordering': ['-created_at'], 'verbose_name': 'پاسخ کاربر', 'verbose_name_plural': 'پاسخ های کاربران'},
        ),
    ]
