# Generated by Django 5.0.6 on 2024-07-01 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0023_alter_useranswer_options'),
        ('exam', '0024_alter_useranswer_options'),
    ]

    operations = [
    ]
