# Generated by Django 5.0.6 on 2024-07-08 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0025_merge_20240701_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalquestion',
            options={'ordering': ['-created_at'], 'verbose_name': 'سوال آزمون عمومی', 'verbose_name_plural': 'سوال های آزمون عمومی'},
        ),
    ]
