# Generated by Django 5.0.6 on 2024-07-08 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0026_alter_generalquestion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalquestionoption',
            options={'ordering': ['-created_at'], 'verbose_name': 'گزینه آزمون عمومی', 'verbose_name_plural': 'گزینه های آزمون عمومی'},
        ),
    ]
