# Generated by Django 5.0.6 on 2024-07-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0027_alter_generalquestionoption_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalquestion',
            name='score',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='امتیاز'),
        ),
    ]
