# Generated by Django 5.0.6 on 2024-07-10 07:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0028_alter_generalquestion_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalquestion',
            name='number',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='شماره'),
        ),
    ]
