# Generated by Django 5.0.6 on 2024-07-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0029_alter_generalquestion_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalexam',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='عنوان'),
        ),
    ]
