# Generated by Django 5.0.6 on 2024-07-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0029_alter_generalquestion_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neooption',
            name='option',
            field=models.CharField(max_length=100, verbose_name='گزینه'),
        ),
    ]
