# Generated by Django 5.0.6 on 2024-07-17 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0030_alter_generalexam_title'),
        ('exam', '0030_alter_neooption_option'),
    ]

    operations = [
    ]
