# Generated by Django 5.0.6 on 2024-07-20 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0031_merge_20240717_1426'),
        ('exam', '0031_merge_20240717_1645'),
    ]

    operations = [
    ]
