# Generated by Django 5.0.6 on 2024-08-21 09:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0032_merge_20240720_1513'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('exam_type', models.CharField(choices=[('P', 'عمومی'), ('E', 'ورودی'), ('B', 'بلبین'), ('N', 'نئو')], max_length=1, verbose_name='نوع آزمون')),
                ('result_file', models.FileField(upload_to='exam/results', verbose_name='فایل نتیجه آزمون')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نتیجه آزمون',
                'verbose_name_plural': 'نتایج آزمون ها',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
